In [ ]:
# some refreshers on python syntax
fake_list = [1, 2, 3, 4, 5]
for i in fake_list:
    print(i)

1
2
3
4
5


In [ ]:
# about numpy:
# numpy arrays: similar to how lists work
my_list = [1, 2, 3, 4]  # a simple list
import numpy as np
my_array = np.array(my_list)  # for numpy arrays, we pass a list into it
print(my_list)
print(my_array)
# for lists, the elements are separated by commas
# for arrays, the elements are separated by blanks
# the difference is that in lists, those are elements
# in arrays, it is a matrix with only one row

[1, 2, 3, 4]
[1 2 3 4]


In [ ]:
# 2D numpy array:
two_d = np.array([[1, 2, 3], [4, 5, 6]])
print(two_d)
# note that I would need to pass the 'lists(matrix row)' into a []
# so it is like nested lists, but in the form of matrices

[[1 2 3]
 [4 5 6]]


In [ ]:
row_sum = np.sum(two_d, axis=1)  # axis=1 means sum row-wise
col_sum = np.sum(two_d, axis=0)  # axis=0 means sum column-wise
print(row_sum)
print(col_sum)

[ 6 15]
[5 7 9]
<class 'numpy.ndarray'>
